# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "thanhlecongg"
repo_name: "arxiv-auto-update"
show_authors: False
show_links: False
show_badge: False
max_results: 15

publish_readme: True
publish_gitpage: True

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Automated Program Repair": 
        filters: ["Automated Program Repair", "Program Repair", "Automated Bug Fixing"]
    "Automated Patch Correctness Assessment": 
        filters: ["Automated Patch Correctness Assessment", "Patch Validation"]
    "Code Summarization": 
        filters: ["Code Summarization", "Code Explanation", "Bug Explanation", "Defect Explanation"]
    "Bug/Vulnerability Management": 
        filters: ["Bug Management", "Vulnerability Management", "Vulnerability-Fixing Commit", "Software Component Analysis"]
    "Regression Bugs/Bug Inducing Commit": 
        filters: ["Bug Inducing Commit", "Regression Bug"]
    "Defect Prediction": 
        filters: ["Defect Prediction"]
