title: SE Paper Daily
description: This page contains the Bug-related SE Papers which is automatically fetched from Arxiv daily at 10:30 GMT+11.
show_downloads: false


## add remote theme
remote_theme: jekyll/minima@v2.5.1

# minima:
skin: dark

plugins:
 - jekyll-remote-theme # add this line to the plugins list if you already have one
 - jekyll-feed
 - jekyll-seo-tag
